# Generated by Django 4.0.5 on 2022-06-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='shortcode',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='url',
            field=models.URLField(),
        ),
    ]
